server {
    listen 80;
    server_name _;

    location = / {
        return 302 /IKEA-project-ver2/;
    }

    location /IKEA-project-ver2/ {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /IKEA-project-ver2/index.html;
    }
}
